<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
        <application>Custom_Administration</application>
        <default>false</default>
        <visible>false</visible>
    </applicationVisibilities>
    <applicationVisibilities>
        <application>Recruiting</application>
        <default>false</default>
        <visible>true</visible>
    </applicationVisibilities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate_Snapshot__c.Candidate_Full_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate_Snapshot__c.Department__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate_Snapshot__c.Stage__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate_Snapshot__c.Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Candidate__c.Batch_Load_Item__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.City__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Country__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Current_Employer__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Currently_Employed__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Drivers_License_Number__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Education__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Email__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Fax__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.First_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Gender__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Last_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Legacy_Candidate_Number__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Mobile__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Phone__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Picture_ID__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Candidate__c.Picture_Link__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Candidate__c.Picture_URL__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Social_Security_Number__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.State_Province__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Street_Address_1__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Street_Address_2__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Tags__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.US_Citizen__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Candidate__c.Unique_Key__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Visa_Required__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Years_of_Experience__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Candidate__c.Zip_Postal_Code__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Interviewer__c.Employee__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Interviewer__c.Position__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Interviewer__c.Role__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Average_Review_Score__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Application__c.Candidate__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Competency_Rating__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Email__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Application__c.Legacy_Application_Number__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Application__c.Needs_References__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Number_of_Job_Applications__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Phone__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Application__c.Position__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Rating__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Application__c.Stage__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Application__c.Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Total_Review_Score__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Application__c.Total_Reviews__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Posting_Site__c.Description__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Posting_Site__c.Job_Site_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Posting_Site__c.Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Posting_Site__c.Technical_Site__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Job_Posting_Site__c.URL__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Posting__c.Job_Posting_Site__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Job_Posting__c.Position__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Actual_Salary__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Additional_Instructions__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Bonus_Percentage__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Offer__c.Candidate_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Job_Application__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Offer__c.Number_of_Offers__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Offer_Date__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Offer_Expiration_Date__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Offer__c.Position_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Offer__c.Stock_Options__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Approval_Matrix__c.Approver_1__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Approval_Matrix__c.Approver_2__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Approval_Matrix__c.Approver_3__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Approval_Matrix__c.Department__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Approval_Matrix__c.Priority__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Approval_Matrix__c.Routing_Key__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Position_Programming_Language__c.Language_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Programming_Language__c.Position__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position_Programming_Language__c.Programming_Language__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Approver_1__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Approver_2__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Approver_3__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Date_Closed__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Date_Opened__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Position__c.Days_Opened__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Department__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Duration__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Education__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Hello__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Hiring_Manager__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Position__c.Job_Description__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Legacy_Position_Number__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Location__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Max_Pay__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Min_Pay__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Position__c.Number_of_Interviewers__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Position__c.Number_of_Positions__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Operating_Systems__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Pay_Grade__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Priority__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Programming_Languages__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Responsibilities__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Skills_Required__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Start_Date__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Sub_Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Position__c.Type__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Programming_Language__c.Description__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Programming_Language__c.Language_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Programming_Language__c.Status__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Reference__c.Email__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Reference__c.First_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Reference__c.Job_Application_Reference__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Reference__c.Last_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Reference__c.Reference_Phone_Number__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Alternate_Position__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Review__c.Candidate_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Cultural_Comments__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Cultural_Fit__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Experience_Comments__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Experience__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Review__c.Interviewer_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Interviewer__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Review__c.Job_Application__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Leadership_Comments__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Leadership_Skills__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Review__c.Overall_Score__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Review__c.Position_Name__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Reason_Recommended__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Recommend_for_Hire__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Review__c.Review_Completed__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Salary__c.Actual_Pay__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Salary__c.Max_Pay__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>false</editable>
        <field>Salary__c.Min_Pay__c</field>
        <hidden>true</hidden>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Salary__c.Position__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>StrikeIronInfo__c.Active__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>StrikeIronInfo__c.Password__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>StrikeIronInfo__c.userID__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Zip_Code__c.City__c</field>
    </fieldLevelSecurities>
    <fieldLevelSecurities>
        <editable>true</editable>
        <field>Zip_Code__c.State__c</field>
    </fieldLevelSecurities>
    <layoutAssingments>
        <layout>Account-Account Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Asset-Asset Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Campaign-Campaign Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Candidate_Snapshot__c-Candidate Snapshot Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Candidate__c-Candidate Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Case-Case Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Contact-Contact Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Contract-Contract Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Event-Event Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Idea-Idea Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Interviewer__c-Interviewer Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Job_Application__c-Job Application Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Job_Posting_Site__c-Job Posting Site Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Job_Posting__c-Job Posting Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Lead-Lead Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Offer__c-Offer Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Opportunity-Opportunity Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>OpportunityLineItem-Opportunity Product Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position_Approval_Matrix__c-Position Approval Matrix Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position_Programming_Language__c-Position Programming Language Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position__c-Approved Position Layout</layout>
        <recordType>Position__c.Approved Non-technical Position Record Type</recordType>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position__c-Approved Technical Position Layout</layout>
        <recordType>Position__c.Approved Technical Position Record Type</recordType>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position__c-Position Layout</layout>
        <recordType>Position__c.Non-Technical Position</recordType>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position__c-Position Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Position__c-Technical Position Layout</layout>
        <recordType>Position__c.Technical Position</recordType>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Product2-Product Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Programming_Language__c-Programming Language Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Reference__c-Reference Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Review__c-Review Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Salary__c-Salary Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Solution-Solution Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>StrikeIronInfo__c-StrikeIronInfo Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Task-Task Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>User-User Layout</layout>
    </layoutAssingments>
    <layoutAssingments>
        <layout>Zip_Code__c-Zip Code Layout</layout>
    </layoutAssingments>
    <objectPermissions>
        <object>Candidate_Snapshot__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Candidate__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Interviewer__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Job_Application__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Job_Posting_Site__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Job_Posting__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Offer__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Position_Approval_Matrix__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Position_Programming_Language__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Position__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Programming_Language__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Reference__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Review__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Salary__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>StrikeIronInfo__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <objectPermissions>
        <object>Zip_Code__c</object>
        <revokeCreate>true</revokeCreate>
        <revokeDelete>true</revokeDelete>
        <revokeEdit>true</revokeEdit>
    </objectPermissions>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Position__c.Approved Non-technical Position Record Type</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Position__c.Approved Technical Position Record Type</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Position__c.Non-Technical Position</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Position__c.Technical Position</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <tabVisibilities>
        <tab>Candidate__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Employee_Referral</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Interviewer__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Job_Application__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Job_Posting_Site__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Job_Posting__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Offer__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Position_Approval_Matrix__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Position_Programming_Language__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Position__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Programming_Language__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Review__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>StrikeIronInfo__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Zip_Code__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
</Profile>
